### ISSUE TITLE
Doesn't build with pandoc 2.1.3

### ISSUE THREAD

**Issue by felixonmars** [lierdakil/pandoc-crossref#169]
```
[ 5 of 20] Compiling Text.Pandoc.CrossRef.Util.Util ( lib/Text/Pandoc/CrossRef/Util/Util.hs, dist/build/test-pandoc-crossref/test-pandoc-crossref-tmp/Text/Pandoc/CrossRef/Util/Util.dyn_o )

lib/Text/Pandoc/CrossRef/Util/Util.hs:40:64: error:
    • Could not deduce (Data.Semigroup.Semigroup a)
        arising from a use of ‘<>’
      from the context: (Eq a, Monoid a, Foldable f)
        bound by the type signature for:
                   intercalate' :: forall a (f :: * -> *).
                                   (Eq a, Monoid a, Foldable f) =>
                                   a -> f a -> a
        at lib/Text/Pandoc/CrossRef/Util/Util.hs:39:1-61
      Possible fix:
        add (Data.Semigroup.Semigroup a) to the context of
          the type signature for:
            intercalate' :: forall a (f :: * -> *).
                            (Eq a, Monoid a, Foldable f) =>
                            a -> f a -> a
    • In the expression: x <> s <> acc
      In the expression: if acc == mempty then x else x <> s <> acc
      In the first argument of ‘foldr’, namely
        ‘(\ x acc -> if acc == mempty then x else x <> s <> acc)’
   |
40 | intercalate' s = foldr (\x acc -> if acc == mempty then x else x <> s <> acc) mempty
   |                                                                ^^^^^^^^^^^^^
```

**Comment by lierdakil** [comment]
Well, that's because Pandoc released a patch-release that breaks compatibility >_< You can try building with GHC 8.4 while I figure out how to work around this mess...

**Comment by lierdakil** [comment]
Nevermind, released v0.3.0.3 which builds fine with pandoc-2.1.3 (but requires it).
