### ISSUE TITLE
Doesn't build with pandoc-types 1.17.5

### ISSUE THREAD

**Issue by felixonmars** [lierdakil/pandoc-crossref#181]
```
[ 3 of 18] Compiling Text.Pandoc.CrossRef.Util.PandocOrphans ( lib/Text/Pandoc/CrossRef/Util/PandocOrphans.hs, dist/build/Text/Pandoc/CrossRef/Util/PandocOrphans.dyn_o )

lib/Text/Pandoc/CrossRef/Util/PandocOrphans.hs:27:30: error:
    Duplicate instance declarations:
      instance [overlapping] ToMetaValue String
        -- Defined at lib/Text/Pandoc/CrossRef/Util/PandocOrphans.hs:27:30
      instance ToMetaValue String -- Defined in ‘Text.Pandoc.Builder’
   |
27 | instance {-# OVERLAPPING #-} ToMetaValue String where
   |                              ^^^^^^^^^^^^^^^^^^
```

**Comment by lierdakil** [comment]
Thanks for reporting. I'll see what I can do.

**Comment by felixonmars** [comment]
I made some changes to pass the build, but it doesn't look like a nice fix, so I didn't submit yet :P
https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/pandoc-crossref&id=658086b2ba2193d02e66aac4be33dc02eead64e9

**Comment by lierdakil** [comment]
Apparently, there's no nice fix as it is. I've created an [issue upstream](https://github.com/jgm/pandoc-types/issues/46). Will try to fudge something later.

**Comment by lierdakil** [comment]
Uploaded a [new candidate](https://hackage.haskell.org/package/pandoc-crossref-0.3.2.1/candidate), will publish if that'll work for you.

**Comment by lierdakil** [comment]
Published https://hackage.haskell.org/package/pandoc-crossref-0.3.2.1 due to no response.

**Comment by felixonmars** [comment]
Ah sorry I forgot this...

The tests are still not passing:

```
Failures:

  test/test-pandoc-crossref.hs:290:25:
  1) LaTeX.Labels Tbl labels
       expected: "\\hypertarget{tbl:some_table1}{}\n\\begin{longtable}[]{@{}@{}}\n\\caption{\\label{tbl:some_table1}A table}\\tabularnewline\n\\toprule\n\\tabularnewline\n\\midrule\n\\endfirsthead\n\\toprule\n\\tabularnewline\n\\midrule\n\\endhead\n\\tabularnewline\n\\bottomrule\n\\end{longtable}\n\ntbl.~\\ref{tbl:some_table1}"
        but got: "\\hypertarget{tbl:some_table1}{}\n\\begin{longtable}[]{@{}@{}}\n\\caption{\\label{tbl:some_table1}A table}\\tabularnewline\n\\toprule\n\\endhead\n\\tabularnewline\n\\bottomrule\n\\end{longtable}\n\ntbl.~\\ref{tbl:some_table1}"

Randomized with seed 866141779

Finished in 0.1087 seconds
49 examples, 1 failure
Test suite test-pandoc-crossref: FAIL
```

**Comment by lierdakil** [comment]
Can you ignore that for now? Pandoc seems happy to change its LaTeX rendering rules between patch revisions, and I'm frankly fed up with it routinely breaking tests, so I'm not going to bother right now -- those will be invariably broken on *some* versions anyway.

**Comment by felixonmars** [comment]
Sure, just wanted to make sure it wasn't my fault somehow :)
