### ISSUE TITLE
Compilation problems with inbound 2.8

### ISSUE THREAD

**Issue by svenevs** [lierdakil/pandoc-crossref#233]
Hey!

So I got some things working [for the dockerfile stuff](https://github.com/pandoc/dockerfiles/pull/50).

1. Latest release here 0.3.4.1 works with pandoc 2.7.3 (ref #232).
2. Changes present on `pandoc@master` produce compilation problems.  [Actual compilation error (scroll way down)](https://circleci.com/gh/pandoc/dockerfiles/201):

    ```
    [1 of 3] Compiling ManData          ( src/ManData.hs, /usr/src/dist-newstyle/build/x86_64-linux/ghc-8.4.3/pandoc-crossref-0.3.4.1/x/pandoc-crossref/build/pandoc-crossref/pandoc-crossref-tmp/ManData.o )

    src/ManData.hs:63:24: error:
        • Couldn't match type ‘T.Text’ with ‘P.Template’
          Expected type: Maybe P.Template
            Actual type: Maybe T.Text
        • In the ‘writerTemplate’ field of a record
          In the first argument of ‘P.writeHtml5String’, namely
            ‘P.def
               {P.writerTemplate = Just t,
                P.writerHighlightStyle = Just pygments}’
          In the second argument of ‘($)’, namely
            ‘P.writeHtml5String
               P.def
                 {P.writerTemplate = Just t,
                  P.writerHighlightStyle = Just pygments}’
       |
    63 |     P.writerTemplate = Just t
       |                        ^^^^^^
    ```
3. I'm fairly certain that [`pandoc` commit `b35fae651145482f1218d32dbea5fffff60e0b0b`](https://github.com/jgm/pandoc/commit/b35fae651145482f1218d32dbea5fffff60e0b0b) is the changeset that actually matters here.  That definitely seems like the most relevant diff.  As you can see on the PR to dockerfile repo I linked I tried to do a manual bisect, but the results are unclear.  Commits that passed the `pandoc` CI failed to build `pandoc` itself in the docker build, but I'm pretty sure that's because of _how_ I'm building `pandoc`, `pandoc-citeproc`, and `pandoc-crossref` together.  Probably something related to [changes in `doctemplates` version requirements](https://github.com/jgm/pandoc/commit/b35fae651145482f1218d32dbea5fffff60e0b0b#diff-d37211f38c72504621b9d03eef12ffd7R411) but I'm not really sure.

I am hoping that you will see the diff in question and error and it makes sense.  I don't actually know any haskell / don't know how to change things.  **But**, if you open a PR here with the changes you think need to happen, I can checkout the PR in the docker build over there and test it for you :slightly_smiling_face:

P.S. It's worth mentioning that after initial hurdle, adding `pandoc-crossref` over there should be generally useful for this project.  We have a `master` branch build of `pandoc` every two weeks, so any breaking changes should be caught relatively quickly.  Hopefully over time as I watch what you do to fix things I will be able to propose PRs myself rather than just file issues!

**Comment by lierdakil** [comment]
Thanks for the heads-up!

This should be a relatively straightforward fix of aligning the datatypes. `getDefaultTemplate` now returns `Text`, but `writerTemplate` expects `Template`, and converting the former into the latter can be done with `compileTemplate`. The caveat: the required change is not at all backwards-compatible. For that specific reason, I'm not inclined to have that in the repo yet: it'll be a hassle with CI and CD.

Side note, this kinda irks me with Pandoc lately -- minor releases can (and do) break public API (which is a big no-no according to [Hackage Package Versioning Policy](https://pvp.haskell.org/)) -- by PVP, the next release must be 2.8 because the types of public functions changed. Otherwise, managing version constraints becomes a huge hassle. /cc @jgm, by the by.

**Comment by jgm** [comment]
@lierdakil We certainly intend to abide by the PVP; have we failed to do that in the past, and if so where?  For the next release, you are right, it must be 2.8.

**Comment by lierdakil** [comment]
@jgm, now that I think about it, the only example in recent memory is pandoc-types 1.17.4 (I think?), which I vaguely remember changed the `(<>)` operator exported from `Text.Pandoc.Builder` due to Monoid/Semigroup change, which broke some code that didn't yet make the Monoid/Semigroup switch. And then I thought I remembered pandoc-types breaking PVP with 1.17.5, but it didn't actually, it just introduced an annoying bug.

Now that I think about it, both examples are about a year old, so "lately" wasn't the right word in the first place. In fact, "lately" everything was pretty good on the PVP front I think. Sorry for the baseless accusation there, I wasn't as active on github this year, so mid-2018 still feels like recent events.

Glad we agree on the next release version number.
